version: "2"
services:
  app:
    environment:
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/elysian
      - RABITMQ_URI=amqp://${MQ_USER}:${MQ_PASSWORD}@mq:5672?heartbeat=2
      - BLOCKSYNC_URI_REST=https://explorer_sdgfutures.ixo.world/api/
      - ETHEREUM_API=https://mainnet.infura.io/
      - ASYM_CYPHER=${ASYMCYPHER}
      - ASYM_KEY=${ASYMKEY}
  db:
    ports:
      - "27017:27017"

  cache:
    ports:
      - "11211:11211"

  mq:
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}

  pol:
    environment:
      - RABITMQ_URI=amqp://${MQ_USER}:${MQ_PASSWORD}@mq:5672?heartbeat=2
      - BLOCKCHAIN_REST=http://blockchain_sdgfutures.ixo.world:1317

  cli:
    environment:
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/elysian
      - BLOCKCHAIN_URI_REST=https://explorer_sdgfutures.ixo.world/api/did/getByDid/
