version: "2"
services:
  app:
    environment:
      - BLOCKSYNC_URI_REST=https://explorer_sdgfuturesuat.ixo.world/api/did/getByDid/
  db:
    ports:
      - "27017:27017"

  cache:
    ports:
      - "11211:11211"

  mq:
    ports:
      - "5672:5672"

  pol:
    environment:
      - BLOCKCHAIN_REST=http://blockchain_sdgfuturesuat.ixo.world:1317

  cli:
    environment:
      - BLOCKCHAIN_URI_REST=https://explorer_sdgfuturesuat.ixo.world/api/did/getByDid/
