version: "2"
services:
  app:
    container_name: app
    image: trustlab/ixo-elysian:master
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://db:27017/elysian
      - MEMCACHE_URI=cache:11211
      - RABITMQ_URI=amqp://guest:guest@mq:5672?heartbeat=2
      - CONFIG=/usr/src/app/config.json
      - TEMPLATE_REPO=https://api.github.com/repos/ixofoundation/schema/contents/
      - VALIDISSUERS=

    ports:
      - "5000:5000"
    restart: always
    links:
      - db
      - cache
      - mq
      - pol
      - cli
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./config.json:/usr/src/app/config.json

  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
      - ./backup:/backup

  cache:
    container_name: cache
    image: memcached:latest
    restart: always

  mq:
    container_name: mq
    image: rabbitmq:latest
    restart: always

  pol:
    container_name: pol
    image: ixoworld/ixo-pol:1.1.3
    environment:
      - RABITMQ_URI=amqp://guest:guest@mq:5672?heartbeat=2
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  cli:
    container_name: cli
    image: trustlab/ixo-cli:master
    environment:
      - MONGODB_URI=mongodb://db:27017/elysian
      - MEMCACHE_URI=cache:11211
