version: "2"
services:
  app:
    environment:
      - BLOCKSYNC_URI_REST=https://explorer_qa.ixo.world/api/
      - ETHEREUM_API=https://ropsten.infura.io/sq19XM5Eu2ANGAzwZ4yk
      - NODEDID=

  db:
    ports:
      - "27017:27017"

  cache:
    ports:
      - "11211:11211"

  mq:
    ports:
      - "5672:5672"

  pol:
    environment:
      - BLOCKCHAIN_REST=http://blockchain_qa.ixo.world:1317

  cli:
    environment:
      - BLOCKCHAIN_URI_REST=https://explorer_qa.ixo.world/api/did/getByDid/
